// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYJwXTwR0dY68k1Nc2AhVW39A49jIRYpY',
    appId: '1:114177811438:web:e5599cbf0f0edfcb5c64ff',
    messagingSenderId: '114177811438',
    projectId: 'c-chat-app-56327',
    authDomain: 'c-chat-app-56327.firebaseapp.com',
    storageBucket: 'c-chat-app-56327.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXaN_ARBXkPj3Aa49Y657sWb1yg6p_RNM',
    appId: '1:114177811438:android:1950ab9f886f677f5c64ff',
    messagingSenderId: '114177811438',
    projectId: 'c-chat-app-56327',
    storageBucket: 'c-chat-app-56327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_SMU7YFqPOeFfAywX-EMme8k0ogtcQ8',
    appId: '1:114177811438:ios:c3186ef38e072cd45c64ff',
    messagingSenderId: '114177811438',
    projectId: 'c-chat-app-56327',
    storageBucket: 'c-chat-app-56327.appspot.com',
    iosClientId: '114177811438-cgg5g09jq3562u491kt0htrdoq72rcec.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneChat',
  );
}
